main: me.Dzyre.mmo.Main
name: MyMMO
author: Dzyre
version: 1.0
api-version: 1.16

commands:
  shop:
    usage: /<command>
  setl:
    usage: /<command>
  unsetl:
    usage: /<command>
  helpbook:
    usage: /<command>
  seti:
    usage: /<command>
  unseti:
    usage: /<command>
  setg:
    usage: /<command>
  unsetg:
    usage: /<command>
  setd:
    usage: /<command>
  unsetd:
    usage: /<command>